// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

type Card struct {
	ID       int32  `json:"id"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
	DeckID   int32  `json:"deck_id"`
}

type Deck struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
